.\"                                      Hey, EMACS: -*- nroff -*-
.\" (C) Copyright 2016 Abdelkrime Aries <kariminfo0@gmail.com>,

.TH DEBPACK 1 "September 13 2016"

.SH NAME
debpack \- Creates Local repo.

.SH SYNOPSIS
.B debpack
.RI "dist-folder"
.RI "dist-name"

.SH DESCRIPTION
This script helps to create a local repository.
.br
It will create a repo in "dists" folder.
.br
This folder will contain the same components in "<dist-folder>" folder.
.br
Duplicate debian package will be sent to "~/pack-tmp/del/" folder.

.SH OPTIONS
.TP
.B dist-folder
The folder where the deb files are.
.TP
.B dist-name
The name we want to use to refer the distribution.
.TP
.B \-h
Show summary of options.

.SH SEE ALSO
.BR debdist (1).
