#!/bin/bash
# Author: Abdelkrime Aries <kariminfo0@gmail.com>
# License: MIT
HOST='\033[02;36m\]\h';
TIME='(\033[01;31m\]\t\033[01;32m\])'
LOCATION='\033[01;34m\]`pwd | sed "s#\(/[^/]\{1,\}/[^/]\{1,\}/[^/]\{1,\}/\).*\(/[^/]\{1,\}/[^/]\{1,\}\)/\{0,1\}#\1_\2#g"`'
PS1=$LOCATION'  '$TIME'\[\033[00m\]\n'$USER'@'$HOST'>> \e[?16;0;200c'
ls --color=al > /dev/null 2>&1 && alias ls='ls -F --color=al' || alias ls='ls -G'
