#!/bin/bash

# ***** Converts pdfs in a given folder to eps using ghost script
# Use: pdf2eps [folder]
#
# Copyright (C) 2018  Abdelkrime Aries <kariminfo0@gmail.com>
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
# http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#

folder=.

if [ ! -z "$1" ]; then
  folder=$1
fi

for i in $folder/*.pdf; do
    echo $i
    gs -q -dNOCACHE -dNOPAUSE -dBATCH -dSAFER -sDEVICE=eps2write -sOutputFile=${i%.*}.eps $i
done
