#!/bin/bash

# ***** Reduce Image Size
# This script helps reducing image size by rreducing,
# its quality to 80%
# Use: redimg <ext>
# <ext>: The image extension, like png, jpg, etc.
# default extension is jpg
#
# Copyright (C) 2013  Abdelkrime Aries <kariminfo0@gmail.com>
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
# http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#

ext=$1
if [ -z "$1" ]; then
  echo "The extension wasn't defined, using jpg by default"
  ext="jpg"
fi
mkdir reduce
for img in *.$ext
  do
    convert "$img" -quality 80 "reduce/$img"
  done
